### ISSUE TITLE
Enable the custom shipping methods 

### ISSUE THREAD

**Issue by vassalloandrea** [solidusio-contrib/solidus_easypost#47]
## Problem

This gem calculates the rates using the Easypost APIs removing the Solidus ones.

## How to solve
Merging the custom rates with the Easypost rates, we can also use the custom shipping methods since Easypost doesn't support the `in-store pickup` and `freight shipping`.

## Roadmap

- [ ] Enable Solidus rates calculator
- [ ] Distinguish the Solidus shipping method from the Easypost ones
- [ ] Buy a rate only if the related shipping method is not `easypost`
- [ ] Disable the `admin_name` shipping method field if it is generated using Easypost
- [ ] Show Easypost errors on the admin panel when shipping is shipped
- [ ] Show Easypost address validation errors on the frontend if occurs

**Comment by brchristian** [comment]
Hi @vassalloandrea, this of critical importance to us. We are stuck on Rails 5.1 because `active_shipping` does not support Rails 5.2. However, we cannot move from `active_shipping` to `solidus_easypost` because we have alternate shipping methods (subscription products that ship later, ebooks that don't ship at all, etc.).

How can I help? Would love to coordinate and get some PRs underway.

**Comment by jarednorman** [comment]
There's some conversation on #111 about getting this issue resolved, but I think we need some clarity about what the current state of this extension is and where @fthobe wants to get it.

**Comment by fthobe** [comment]
@jarednorman I don't see how we can live without even a basic enum defining between: 
- manual shipping methods
- externally powered ones

That is extended by the extensions. 
Easypost has some quiet aggressive automatisms regarding the shipping methods that we are currently removing like 
- creating shipping methods without beeing asked
- overriding the default shipping calculator aggressively 

When we are done with that I take a look.

**Comment by jarednorman** [comment]
You're very focused on the implementation (involving an enum). I'm trying to understand the desired functionality.

Am I correct in understanding that you want a way to distinguish shipping methods that use the built-in calculator-based system and different external services (provided by extensions)?

An enum is tricky for that because it's not something you can add/remove values from dynamically in different extensions, but there's other ways we could provide the same effect.

**Comment by fthobe** [comment]
TBH honest, I am absolutely open for alternatives here.

Yes, you framed the issue correctly, just yesterday I was hanging with people selling furniture ranging from lamps to couches.

Different shipper, broker, label generation, to make something work for them they'd need two to three different platforms like shipstation or easypost all for different weight and volume scales. For @vassalloandrea the problem was more the aggressive tactics of easypost in overriding [the shipping price](https://github.com/solidusio-contrib/solidus_easypost/blob/d1eca53f08f32316d0caf5b4c36c7451d9032614/lib/solidus_easypost/estimator.rb#L30) with [this default](https://github.com/solidusio-contrib/solidus_easypost/blob/master/lib/solidus_easypost/shipping_rate_calculator.rb) for all easypost shipping methods defaulted to this, but in general this extension was rather opinionated in the implementation, in general [what @mamhoff did was rather cool too](https://github.com/friendlycart/friendly_shipping), writing it's own wrapper around the API. The problem is as soon as more than one broker is needed it gets hairy quickly and some form of installed_shipping_brokers with an association of eg a shipping method to easypost might be very handy.
